# -*- coding: utf-8 -*-
"""game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gW7T9Pg1FVR5JFlkZjemyItKPEl4PB7i
"""

# ============================================================
# FINANCIAL TRADER
# Streamlit + Pygame + yfinance
# ============================================================

import streamlit as st
import yfinance as yf
import pygame
import numpy as np
import pandas as pd
import random
import time

# ============================================================
# CONFIGURACIÓN
# ============================================================

st.set_page_config(
    page_title="Financial Trader",
    page_icon="📈",
    layout="centered"
)

# ============================================================
# INICIALIZAR PYGAME
# ============================================================
# Pygame se utiliza para la lógica gráfica del videojuego.
# No se abre una ventana de Pygame en el celular.
# Streamlit muestra la interfaz en el navegador.

pygame.init()

ANCHO = 800
ALTO = 600

# Superficie virtual de Pygame
SUPERFICIE = pygame.Surface((ANCHO, ALTO))


# ============================================================
# ACTIVOS
# ============================================================

ACTIVOS = {

    "BIMBOA.MX": "Grupo Bimbo",

    "WALMEX.MX": "Walmart México",

    "FEMSAUBD.MX": "FEMSA",

    "GMEXICOB.MX": "Grupo México",

    "BTC-USD": "Bitcoin"
}


# ============================================================
# FUNCIONES YFINANCE
# ============================================================

@st.cache_data(ttl=300)
def obtener_datos(ticker):

    try:

        datos = yf.download(
            ticker,
            period="3mo",
            interval="1d",
            auto_adjust=True,
            progress=False
        )

        if datos.empty:
            return None

        # Manejar MultiIndex de yfinance
        if isinstance(datos.columns, pd.MultiIndex):

            precios = datos["Close"]

            if isinstance(precios, pd.DataFrame):
                precios = precios.iloc[:, 0]

        else:

            precios = datos["Close"]

        precios = precios.dropna()

        return precios

    except Exception:

        return None


# ============================================================
# INICIAR JUEGO
# ============================================================

def iniciar_juego():

    st.session_state.jugando = True

    st.session_state.ronda = 1

    st.session_state.max_rondas = 20

    st.session_state.efectivo = 100000.0

    st.session_state.capital_inicial = 100000.0

    st.session_state.cartera = {
        ticker: 0
        for ticker in ACTIVOS
    }

    st.session_state.precios = {}

    st.session_state.historial = []

    st.session_state.decision = "Esperando decisión..."

    st.session_state.evento = generar_evento()

    # Obtener precios reales
    for ticker in ACTIVOS:

        datos = obtener_datos(ticker)

        if datos is not None and len(datos) > 0:

            st.session_state.precios[ticker] = float(
                datos.iloc[-1]
            )

        else:

            # Precio alternativo
            st.session_state.precios[ticker] = 100.0


# ============================================================
# EVENTOS FINANCIEROS
# ============================================================

def generar_evento():

    eventos = [

        (
            "BANXICO REDUCE LA TASA",
            "Menores tasas favorecen el apetito por riesgo.",
            1.015
        ),

        (
            "BANXICO AUMENTA LA TASA",
            "Las tasas elevadas presionan a los activos de riesgo.",
            0.985
        ),

        (
            "INFLACIÓN AL ALZA",
            "La inflación genera incertidumbre en los mercados.",
            0.975
        ),

        (
            "CRECIMIENTO ECONÓMICO",
            "Los indicadores muestran una economía más fuerte.",
            1.025
        ),

        (
            "CRISIS FINANCIERA",
            "Los mercados internacionales presentan caídas.",
            0.940
        ),

        (
            "RALLY BURSÁTIL",
            "Los inversionistas aumentan su exposición al riesgo.",
            1.040
        ),

        (
            "ESTABILIDAD",
            "Los mercados presentan movimientos moderados.",
            1.000
        )
    ]

    nombre, descripcion, factor = random.choice(eventos)

    return {
        "nombre": nombre,
        "descripcion": descripcion,
        "factor": factor
    }


# ============================================================
# VALOR DEL PORTAFOLIO
# ============================================================

def calcular_portafolio():

    valor = st.session_state.efectivo

    for ticker in ACTIVOS:

        unidades = st.session_state.cartera[ticker]

        precio = st.session_state.precios[ticker]

        valor += unidades * precio

    return valor


# ============================================================
# COMPRAR
# ============================================================

def comprar(ticker, cantidad):

    precio = st.session_state.precios[ticker]

    costo = precio * cantidad

    if costo <= st.session_state.efectivo:

        st.session_state.efectivo -= costo

        st.session_state.cartera[ticker] += cantidad

        st.session_state.decision = (
            f"Compraste {cantidad} unidades de "
            f"{ACTIVOS[ticker]}."
        )

    else:

        st.session_state.decision = (
            "No tienes suficiente efectivo."
        )


# ============================================================
# VENDER
# ============================================================

def vender(ticker, cantidad):

    disponibles = st.session_state.cartera[ticker]

    if cantidad <= disponibles:

        precio = st.session_state.precios[ticker]

        ingreso = precio * cantidad

        st.session_state.efectivo += ingreso

        st.session_state.cartera[ticker] -= cantidad

        st.session_state.decision = (
            f"Vendiste {cantidad} unidades de "
            f"{ACTIVOS[ticker]}."
        )

    else:

        st.session_state.decision = (
            "No tienes suficientes unidades."
        )


# ============================================================
# ACTUALIZAR PRECIOS
# ============================================================

def actualizar_precios():

    factor_evento = st.session_state.evento["factor"]

    for ticker in ACTIVOS:

        precio_actual = st.session_state.precios[ticker]

        # Parámetros de volatilidad
        if ticker == "BTC-USD":

            sigma = 0.045

        elif ticker == "GMEXICOB.MX":

            sigma = 0.025

        elif ticker == "WALMEX.MX":

            sigma = 0.018

        elif ticker == "BIMBOA.MX":

            sigma = 0.015

        else:

            sigma = 0.012

        # Movimiento Geométrico Browniano

        mu = 0.0003

        Z = np.random.normal()

        retorno = (
            mu
            - 0.5 * sigma**2
            + sigma * Z
        )

        nuevo_precio = (
            precio_actual
            * np.exp(retorno)
        )

        # Impacto del evento
        nuevo_precio *= factor_evento

        st.session_state.precios[ticker] = nuevo_precio


# ============================================================
# SIGUIENTE RONDA
# ============================================================

def siguiente_ronda():

    valor = calcular_portafolio()

    st.session_state.historial.append({

        "Ronda": st.session_state.ronda,

        "Patrimonio": valor

    })

    # Cambiar precios
    actualizar_precios()

    st.session_state.ronda += 1

    if st.session_state.ronda > st.session_state.max_rondas:

        st.session_state.jugando = False

    else:

        st.session_state.evento = generar_evento()

        st.session_state.decision = (
            "Esperando decisión..."
        )


# ============================================================
# TÍTULO
# ============================================================

st.title("FINANCIAL TRADER")

st.write(
    "Videojuego educativo de inversión y mercados financieros"
)


# ============================================================
# PANTALLA INICIAL
# ============================================================

if "jugando" not in st.session_state:

    st.subheader("¿Puedes vencer al mercado?")

    st.write(
        """
        Comienzas con **$100,000 MXN**.

        Durante 20 rondas tendrás que tomar decisiones
        de inversión utilizando información del mercado.

        Los precios iniciales se obtienen mediante
        **Yahoo Finance**.
        """
    )

    st.info(
        "Objetivo: terminar las 20 rondas con el mayor "
        "patrimonio posible."
    )

    if st.button(
        "INICIAR PARTIDA",
        use_container_width=True
    ):

        iniciar_juego()

        st.rerun()

    st.stop()


# ============================================================
# FINAL DEL JUEGO
# ============================================================

if not st.session_state.jugando:

    valor_final = calcular_portafolio()

    rendimiento = (
        (valor_final - st.session_state.capital_inicial)
        / st.session_state.capital_inicial
        * 100
    )

    st.success("PARTIDA TERMINADA")

    st.metric(
        "Patrimonio final",
        f"${valor_final:,.2f}"
    )

    st.metric(
        "Rendimiento",
        f"{rendimiento:.2f}%"
    )

    if rendimiento > 20:

        st.balloons()

        st.success(
            "Excelente desempeño."
        )

    elif rendimiento > 0:

        st.info(
            "Terminaste con rendimiento positivo."
        )

    else:

        st.warning(
            "Tu patrimonio terminó por debajo "
            "del capital inicial."
        )

    # --------------------------------------------------------
    # GRÁFICA
    # --------------------------------------------------------

    if st.session_state.historial:

        df = pd.DataFrame(
            st.session_state.historial
        )

        st.subheader(
            "Evolución del patrimonio"
        )

        st.line_chart(
            df.set_index("Ronda")
        )

    if st.button(
        "NUEVA PARTIDA",
        use_container_width=True
    ):

        iniciar_juego()

        st.rerun()

    st.stop()


# ============================================================
# PANEL SUPERIOR
# ============================================================

valor_actual = calcular_portafolio()

rendimiento = (
    (valor_actual - st.session_state.capital_inicial)
    / st.session_state.capital_inicial
    * 100
)

col1, col2, col3 = st.columns(3)

with col1:

    st.metric(
        "Patrimonio",
        f"${valor_actual:,.0f}"
    )

with col2:

    st.metric(
        "Efectivo",
        f"${st.session_state.efectivo:,.0f}"
    )

with col3:

    st.metric(
        "Rendimiento",
        f"{rendimiento:.2f}%"
    )


# ============================================================
# RONDA
# ============================================================

st.progress(
    min(
        st.session_state.ronda
        / st.session_state.max_rondas,
        1.0
    )
)

st.write(
    f"### Ronda {st.session_state.ronda} "
    f"de {st.session_state.max_rondas}"
)


# ============================================================
# EVENTO ECONÓMICO
# ============================================================

evento = st.session_state.evento

st.subheader(
    f"EVENTO: {evento['nombre']}"
)

st.write(
    evento["descripcion"]
)


# ============================================================
# MERCADO
# ============================================================

st.subheader("Mercado")

datos = []

for ticker in ACTIVOS:

    datos.append({

        "Ticker": ticker,

        "Activo": ACTIVOS[ticker],

        "Precio": st.session_state.precios[ticker],

        "Posición": st.session_state.cartera[ticker]

    })

df = pd.DataFrame(datos)

st.dataframe(
    df,
    hide_index=True,
    use_container_width=True,
    column_config={
        "Precio": st.column_config.NumberColumn(
            format="$%.2f"
        )
    }
)


# ============================================================
# DECISIÓN
# ============================================================

st.subheader("Toma una decisión")

ticker = st.selectbox(
    "Selecciona un activo",
    list(ACTIVOS.keys()),
    format_func=lambda x:
        f"{x} — {ACTIVOS[x]}"
)

precio = st.session_state.precios[ticker]

st.write(
    f"**Precio:** ${precio:,.2f}"
)

cantidad = st.number_input(
    "Cantidad",
    min_value=1,
    value=1,
    step=1
)

col1, col2, col3 = st.columns(3)

with col1:

    if st.button(
        "COMPRAR",
        use_container_width=True
    ):

        comprar(
            ticker,
            cantidad
        )

        st.rerun()


with col2:

    if st.button(
        "VENDER",
        use_container_width=True
    ):

        vender(
            ticker,
            cantidad
        )

        st.rerun()


with col3:

    if st.button(
        "MANTENER",
        use_container_width=True
    ):

        st.session_state.decision = (
            f"Mantienes tu posición en "
            f"{ACTIVOS[ticker]}."
        )


# ============================================================
# DECISIÓN
# ============================================================

st.info(
    st.session_state.decision
)


# ============================================================
# PORTAFOLIO
# ============================================================

st.subheader("Mi portafolio")

datos_portafolio = []

for ticker in ACTIVOS:

    unidades = st.session_state.cartera[ticker]

    precio = st.session_state.precios[ticker]

    valor = unidades * precio

    datos_portafolio.append({

        "Activo": ACTIVOS[ticker],

        "Ticker": ticker,

        "Unidades": unidades,

        "Precio": precio,

        "Valor": valor

    })

df_portafolio = pd.DataFrame(
    datos_portafolio
)

st.dataframe(
    df_portafolio,
    hide_index=True,
    use_container_width=True,
    column_config={

        "Precio":
            st.column_config.NumberColumn(
                format="$%.2f"
            ),

        "Valor":
            st.column_config.NumberColumn(
                format="$%.2f"
            )
    }
)


# ============================================================
# AVANZAR
# ============================================================

st.divider()

if st.button(
    "AVANZAR A LA SIGUIENTE RONDA",
    use_container_width=True
):

    siguiente_ronda()

    st.rerun()


# ============================================================
# INFORMACIÓN DIDÁCTICA
# ============================================================

with st.expander(
    "¿Qué modelo financiero utiliza el juego?"
):

    st.write(
        """
        Los precios se simulan utilizando el
        Movimiento Geométrico Browniano.
        """
    )

    st.latex(
        r"""
        S_{t+1}=S_t
        \exp\left[
        \left(\mu-\frac{1}{2}\sigma^2\right)
        +\sigma Z_t
        \right]
        """
    )

    st.write(
        """
        donde:

        μ = rendimiento esperado

        σ = volatilidad

        Z = variable aleatoria normal estándar
        """
    )

    st.latex(
        r"""
        R=\frac{V_f-V_0}{V_0}\times100
        """
    )

    st.write(
        "El objetivo es maximizar el rendimiento "
        "sin asumir que un mayor riesgo siempre "
        "produce un mayor rendimiento."
    )