# -*- coding: utf-8 -*-
"""game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gW7T9Pg1FVR5JFlkZjemyItKPEl4PB7i
"""

import streamlit as st
import yfinance as yf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
import random

# ============================================================
# CONFIGURACIÓN
# ============================================================

st.set_page_config(
    page_title="Financial Trader",
    page_icon="📈",
    layout="wide"
)



# ============================================================
# ESTILO
# ============================================================

st.markdown("""
<style>

.main {
    background-color: #0e1117;
}

.block-container {
    padding-top: 1rem;
}

.metric-card {
    background-color: #161b22;
    padding: 15px;
    border-radius: 10px;
    border: 1px solid #30363d;
}

.market-card {
    background-color: #161b22;
    padding: 15px;
    border-radius: 10px;
    margin-bottom: 10px;
    border: 1px solid #30363d;
}

.event-card {
    background-color: #292313;
    padding: 15px;
    border-radius: 10px;
    border: 1px solid #66551c;
}

</style>
""", unsafe_allow_html=True)


# ============================================================
# ACTIVOS
# ============================================================

ACTIVOS = {
    "BIMBOA.MX": "Grupo Bimbo",
    "WALMEX.MX": "Walmart México",
    "FEMSAUBD.MX": "FEMSA",
    "GMEXICOB.MX": "Grupo México",
    "GENTERA.MX": "Gentera"
}


# ============================================================
# DESCARGAR DATOS HISTÓRICOS
# ============================================================

@st.cache_data(ttl=3600)
def descargar_datos(ticker, periodo):

    datos = yf.download(
        ticker,
        period=periodo,
        interval="1d",
        auto_adjust=True,
        progress=False
    )

    if datos.empty:
        return None

    # Resolver posibles MultiIndex de yfinance
    if isinstance(datos.columns, pd.MultiIndex):

        if "Close" in datos.columns.get_level_values(0):
            cierre = datos["Close"]

            if isinstance(cierre, pd.DataFrame):
                cierre = cierre.iloc[:, 0]

        else:
            cierre = datos.iloc[:, 0]

    else:

        cierre = datos["Close"]

    cierre = pd.Series(cierre).dropna()

    return cierre


# ============================================================
# CALCULAR PARÁMETROS HISTÓRICOS
# ============================================================

@st.cache_data(ttl=3600)
def parametros_historicos(ticker, periodo):

    precios = descargar_datos(ticker, periodo)

    if precios is None or len(precios) < 30:
        return None

    # Rendimientos logarítmicos
    rendimientos = np.log(
        precios / precios.shift(1)
    ).dropna()

    # Media diaria
    mu_diaria = rendimientos.mean()

    # Volatilidad diaria
    sigma_diaria = rendimientos.std()

    # Parámetros anualizados
    mu_anual = mu_diaria * 252

    sigma_anual = sigma_diaria * np.sqrt(252)

    precio_actual = float(precios.iloc[-1])

    return {
        "precio": precio_actual,
        "mu_diaria": float(mu_diaria),
        "sigma_diaria": float(sigma_diaria),
        "mu_anual": float(mu_anual),
        "sigma_anual": float(sigma_anual),
        "historial": precios,
        "rendimientos": rendimientos
    }


# ============================================================
# SESIÓN
# ============================================================

if "iniciado" not in st.session_state:

    st.session_state.iniciado = False

if "ronda" not in st.session_state:

    st.session_state.ronda = 1

if "efectivo" not in st.session_state:

    st.session_state.efectivo = 10000.0

if "cartera" not in st.session_state:

    st.session_state.cartera = {
        ticker: 0
        for ticker in ACTIVOS
    }

if "precios" not in st.session_state:

    st.session_state.precios = {}

if "historial_patrimonio" not in st.session_state:

    st.session_state.historial_patrimonio = [
        100000.0
    ]

if "eventos" not in st.session_state:

    st.session_state.eventos = []

if "evento_actual" not in st.session_state:

    st.session_state.evento_actual = (
        "El mercado abre con normalidad."
    )

if "mensaje" not in st.session_state:

    st.session_state.mensaje = ""


# ============================================================
# FUNCIONES DEL JUEGO
# ============================================================

def valor_cartera():

    total = 0

    for ticker in ACTIVOS:

        cantidad = st.session_state.cartera[ticker]

        precio = st.session_state.precios.get(
            ticker,
            0
        )

        total += cantidad * precio

    return total


def patrimonio():

    return (
        st.session_state.efectivo
        + valor_cartera()
    )


def rendimiento():

    return (
        patrimonio() / 10000 - 1
    ) * 100


# ============================================================
# COMPRAR
# ============================================================

def comprar(ticker, cantidad):

    precio = st.session_state.precios[ticker]

    costo = precio * cantidad

    if costo <= st.session_state.efectivo:

        st.session_state.cartera[ticker] += cantidad

        st.session_state.efectivo -= costo

        st.session_state.mensaje = (
            f"Compraste {cantidad} unidad(es) de "
            f"{ACTIVOS[ticker]}."
        )

    else:

        st.session_state.mensaje = (
            "No tienes suficiente efectivo."
        )


# ============================================================
# VENDER
# ============================================================

def vender(ticker, cantidad):

    if (
        cantidad
        <= st.session_state.cartera[ticker]
    ):

        precio = st.session_state.precios[ticker]

        ingreso = precio * cantidad

        st.session_state.cartera[ticker] -= cantidad

        st.session_state.efectivo += ingreso

        st.session_state.mensaje = (
            f"Vendiste {cantidad} unidad(es) de "
            f"{ACTIVOS[ticker]}."
        )

    else:

        st.session_state.mensaje = (
            "No tienes suficientes unidades."
        )


# ============================================================
# EVENTOS ECONÓMICOS
# ============================================================

EVENTOS = [

    (
        "Inflación aumenta",
        "La inflación supera las expectativas.",
        -0.015
    ),

    (
        "Recorte de tasas",
        "El banco central reduce las tasas.",
        0.012
    ),

    (
        "Crisis internacional",
        "Aumenta la incertidumbre financiera.",
        -0.025
    ),

    (
        "Datos económicos positivos",
        "La economía muestra fortaleza.",
        0.018
    ),

    (
        "Mercados estables",
        "Los mercados operan con estabilidad.",
        0.002
    ),

    (
        "Auge de activos de riesgo",
        "Aumenta la demanda de activos de riesgo.",
        0.020
    )
]


# ============================================================
# SIGUIENTE RONDA
# ============================================================

def siguiente_ronda():

    if st.session_state.ronda >= 20:

        st.session_state.mensaje = (
            "La partida ha terminado."
        )

        return

    evento = random.choice(EVENTOS)

    nombre_evento = evento[0]

    descripcion = evento[1]

    factor = evento[2]

    st.session_state.evento_actual = (
        f"{nombre_evento}: {descripcion}"
    )

    # --------------------------------------------------------
    # SIMULACIÓN CON SIGMA HISTÓRICA
    # --------------------------------------------------------

    for ticker in ACTIVOS:

        parametros = parametros_historicos(
            ticker,
            periodo_hist
        )

        if parametros is None:
            continue

        mu = parametros["mu_diaria"]

        sigma = parametros["sigma_diaria"]

        Z = np.random.normal(0, 1)

        # MGB
        rendimiento_simulado = (
            mu
            - 0.5 * sigma**2
            + sigma * Z
            + factor
        )

        precio_actual = (
            st.session_state.precios[ticker]
        )

        nuevo_precio = precio_actual * math.exp(
            rendimiento_simulado
        )

        st.session_state.precios[ticker] = max(
            nuevo_precio,
            0.01
        )

    st.session_state.ronda += 1

    st.session_state.historial_patrimonio.append(
        patrimonio()
    )

    st.session_state.eventos.append(
        {
            "Ronda": st.session_state.ronda,
            "Evento": nombre_evento,
            "Patrimonio": patrimonio()
        }
    )

    st.session_state.mensaje = (
        f"Comenzó la ronda {st.session_state.ronda}."
    )


# ============================================================
# INICIO
# ============================================================
st.title("")

st.image("UNRC.png", caption="Universidad Nacional Rosario Castellanos", width=300)

st.title("FINANCIAL TRADER")

st.subheader(
    "Simulación Bursátil y Avanzada en Finanzas"
)


# ============================================================
# CONFIGURACIÓN
# ============================================================

if not st.session_state.iniciado:

    st.write(
        """
        Bienvenido al mercado.

        Comenzarás con **$10,000 MXN** y tendrás que
        tomar decisiones de inversión durante 20 rondas.

        Los parámetros de riesgo de cada activo se calculan
        utilizando sus rendimientos históricos reales.
        """
    )

    periodo_hist = st.selectbox(
        "Periodo histórico para calcular la volatilidad",
        [
            "6mo",
            "1y",
            "2y",
            "5y"
        ],
        index=2
    )

    if st.button(
        "INICIAR PARTIDA",
        type="primary",
        use_container_width=True
    ):

        with st.spinner(
            "Descargando datos históricos..."
        ):

            for ticker in ACTIVOS:

                parametros = parametros_historicos(
                    ticker,
                    periodo_hist
                )

                if parametros is not None:

                    st.session_state.precios[ticker] = (
                        parametros["precio"]
                    )

        if len(st.session_state.precios) == len(ACTIVOS):

            st.session_state.iniciado = True

            st.rerun()

        else:

            st.error(
                "No fue posible obtener todos los precios."
            )

    st.stop()


# ============================================================
# VARIABLES DE JUEGO
# ============================================================

# Mantener disponible para siguiente_ronda
if "periodo_hist" not in st.session_state:

    st.session_state.periodo_hist = "2y"

periodo_hist = st.session_state.get(
    "periodo_hist",
    "2y"
)


# ============================================================
# MÉTRICAS
# ============================================================

col1, col2, col3, col4 = st.columns(4)

col1.metric(
    "Ronda",
    f"{st.session_state.ronda} / 20"
)

col2.metric(
    "Efectivo",
    f"${st.session_state.efectivo:,.2f}"
)

col3.metric(
    "Portafolio",
    f"${valor_cartera():,.2f}"
)

col4.metric(
    "Rendimiento",
    f"{rendimiento():+.2f}%"
)


st.divider()


# ============================================================
# EVENTO
# ============================================================

st.markdown(
    f"""
    <div class="event-card">
    <b>EVENTO DE MERCADO</b><br><br>
    {st.session_state.evento_actual}
    </div>
    """,
    unsafe_allow_html=True
)


st.divider()


# ============================================================
# MERCADO
# ============================================================

st.header("Mercado")


for ticker, nombre in ACTIVOS.items():

    parametros = parametros_historicos(
        ticker,
        periodo_hist
    )

    if parametros is None:
        continue

    precio = st.session_state.precios[ticker]

    sigma_d = parametros["sigma_diaria"]

    sigma_a = parametros["sigma_anual"]

    mu_d = parametros["mu_diaria"]

    cantidad = st.session_state.cartera[ticker]

    col1, col2, col3, col4, col5 = st.columns(
        [2.2, 1.3, 1.3, 1.5, 2]
    )

    with col1:

        st.markdown(
            f"**{nombre}**  \n"
            f"`{ticker}`"
        )

    with col2:

        st.write(
            f"**${precio:,.2f}**"
        )

    with col3:

        st.write(
            f"σ diaria  \n"
            f"**{sigma_d*100:.2f}%**"
        )

    with col4:

        st.write(
            f"σ anual  \n"
            f"**{sigma_a*100:.2f}%**"
        )

    with col5:

        st.write(
            f"Posición: **{cantidad}**"
        )


        c1, c2 = st.columns(2)

        with c1:

            if st.button(
                "COMPRAR",
                key=f"buy_{ticker}",
                use_container_width=True
            ):

                comprar(ticker, 1)

                st.rerun()

        with c2:

            if st.button(
                "VENDER",
                key=f"sell_{ticker}",
                use_container_width=True
            ):

                vender(ticker, 1)

                st.rerun()


st.divider()


# ============================================================
# INFORMACIÓN DE RIESGO
# ============================================================

st.header("Riesgo histórico")

st.write(
    """
    La volatilidad σ se obtiene a partir de los
    **rendimientos logarítmicos históricos**:
    """
)

st.latex(
    r"""
    r_t=\ln\left(\frac{S_t}{S_{t-1}}\right)
    """
)

st.write(
    "La volatilidad diaria se calcula como:"
)

st.latex(
    r"""
    \sigma_d =
    \operatorname{Std}(r_t)
    """
)

st.write(
    "Y la volatilidad anualizada:"
)

st.latex(
    r"""
    \sigma_a =
    \sigma_d\sqrt{252}
    """
)


# ============================================================
# GRÁFICA DEL PATRIMONIO
# ============================================================

st.header("Evolución del patrimonio")

fig, ax = plt.subplots(
    figsize=(10, 4)
)

ax.plot(
    range(
        len(
            st.session_state.historial_patrimonio
        )
    ),
    st.session_state.historial_patrimonio,
    marker="o"
)

ax.axhline(
    100000,
    linestyle="--"
)

ax.set_xlabel("Ronda")

ax.set_ylabel("Patrimonio ($)")

ax.grid(True, alpha=0.2)

st.pyplot(fig)


# ============================================================
# CARTERA
# ============================================================

st.header("Mi cartera")

datos_cartera = []

for ticker, nombre in ACTIVOS.items():

    cantidad = st.session_state.cartera[ticker]

    precio = st.session_state.precios[ticker]

    valor = cantidad * precio

    datos_cartera.append(
        [
            nombre,
            ticker,
            cantidad,
            precio,
            valor
        ]
    )

df_cartera = pd.DataFrame(
    datos_cartera,
    columns=[
        "Activo",
        "Ticker",
        "Unidades",
        "Precio",
        "Valor"
    ]
)

st.dataframe(
    df_cartera,
    use_container_width=True,
    hide_index=True
)


# ============================================================
# MENSAJE
# ============================================================

if st.session_state.mensaje:

    st.info(
        st.session_state.mensaje
    )


# ============================================================
# SIGUIENTE RONDA
# ============================================================

st.divider()

if st.session_state.ronda < 20:

    if st.button(
        "SIGUIENTE RONDA",
        type="primary",
        use_container_width=True
    ):

        siguiente_ronda()

        st.rerun()

else:

    st.success(
        f"""
        PARTIDA TERMINADA

        Patrimonio final:
        **${patrimonio():,.2f}**

        Rendimiento:
        **{rendimiento():+.2f}%**
        """
    )


# ============================================================
# DATOS DE LOS EVENTOS
# ============================================================

if st.session_state.eventos:

    st.header("Historial de eventos")

    df_eventos = pd.DataFrame(
        st.session_state.eventos
    )

    st.dataframe(
        df_eventos,
        use_container_width=True,
        hide_index=True
    )
